services:

  redis:
    image: redis:7.4.2
    container_name: "redis-container"
    networks:
      - hanjari-network

  hanjari:
    image: hanjari-prod:latest
    container_name: "hanjari-container"
    env_file:
      - .env
    networks:
      - hanjari-network
    depends_on:
      - redis
    ports:
      - "8080:8080"

networks:
  hanjari-network:
    external: true
