services:

  redis:
    image: redis:7.4.2
    container_name: "redis-container"
    networks:
      - hanjari-network

  hanjari:
    image: hanjari-dev:latest
    container_name: "hanjari-container"
    env_file:
      - .env
    networks:
      - hanjari-network
    depends_on:
      - redis

  nginx:
    image: nginx:1.27.4
    container_name: "nginx-container"
    volumes:
      - ~/hanjari/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ~/hanjari/nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt/live/prod.backend.hanjari.site/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /etc/letsencrypt/live/prod.backend.hanjari.site/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
    networks:
      - hanjari-network
    depends_on:
      - hanjari
    ports:
      - "80:80"
      - "443:443"

networks:
  hanjari-network:
    external: true
