name: Dev Deployment

on:
  workflow_run:
    workflows: ["Dev Integration"]
    types:
      - completed
    
jobs:
  deploy:
  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: hanjari-dev

      - name: Generate .env
        run: |
          echo "${{ secrets.DEV_ENV }}" > .env
          echo "${{ secrets.DEV_MYSQL_ENV }}" > mysql.env

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/${{secrets.DOCKER_DEV_REPO}}:latest .

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_DEV_REPO }}:latest

      - name: Copy file to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEV_EC2_HOST }}
          username: ${{ secrets.DEV_EC2_USERNAME }}
          key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
          source: ".env,mysql.env,docker-compose.yml"
          target: ${{ secrets.DEV_EC2_PROJECT_PATH }}
        
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DEV_EC2_HOST }}
          username: ${{ secrets.DEV_EC2_USERNAME }}
          key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.DEV_EC2_PROJECT_PATH }}
            echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
            docker compose down
            docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_DEV_REPO }}:latest
            docker compose up -d
            
